### ISSUE TITLE
Ezzybot cannot be ran twice

### ISSUE THREAD

**Issue by itslukej** [Azure-Developments/ezzybot#46]
Well, it can be ran twice.. but the second ezzybot would be pointless. The hook.events is global and is shared between each bot(this shouldn't happen) and messes up running multiple ezzybot instances

**Comment by mission712** [comment]
this would be most likely fixed by keeping variables in the scope. python currently shares the environment with multiple programs.

**Comment by itslukej** [comment]
I have tested this recently, this issue doesn't seem to be present with the new reloading method.
